/**
 * Image + audio discovery for realms.
 *
 * ALL realm data comes from the pre-built manifest at lib/data/realms-manifest.json
 * (generated by scripts/generate-realm-manifest.js via the "prebuild" npm script).
 *
 * NO runtime fs calls for realm data → Next.js output-file-tracing cannot bundle
 * public/realms/** into serverless functions, keeping bundles well under limits.
 *
 * discoverPageArt / discoverPageOverlay still use fs because they read from
 * public/art/[page]/ which is tiny and is NOT the cause of bundle bloat.
 */

import fs from 'fs'
import path from 'path'
import manifest from '@/lib/data/realms-manifest.json'

export { discoverRealmCardImage, discoverRealmHeroImage } from '@/lib/utils/realmMeta'

export interface DiscoveredImages {
  gallery: string[]
  lore: string[]
  characters: string[]
  band?: string
}

export interface DiscoveredAudioTrack {
  id: string
  title: string
  url: string
  filename: string
  duration?: string
}

type ManifestRealm = {
  gallery: string[]
  lore: string[]
  characters: string[]
  audio: DiscoveredAudioTrack[]
}

type Manifest = {
  realms: Record<string, ManifestRealm>
  audio: Record<string, DiscoveredAudioTrack[]>
}

const m = manifest as Manifest

function realmData(slug: string): ManifestRealm {
  return m.realms[slug] ?? { gallery: [], lore: [], characters: [], audio: [] }
}

export function discoverRealmImages(slug: string): DiscoveredImages {
  const d = realmData(slug)
  return {
    gallery: d.gallery,
    lore: d.lore,
    characters: d.characters,
    band: d.gallery[0],
  }
}

// seq/ not in manifest — returns empty; callers that need seq should use manifest directly
export function discoverRealmSequence(_slug: string): string[] {
  return []
}

export function discoverRealmAudio(slug: string): DiscoveredAudioTrack[] {
  const d = realmData(slug)
  if (d.audio.length > 0) return d.audio
  return m.audio[slug] ?? []
}

// ── Page art (public/art/) — still uses fs, tiny folder, not causing bundle bloat ──

const IMG_RE = /\.(jpg|jpeg|png|webp|avif|gif)$/i

function listImages(dir: string, urlBase: string): string[] {
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir).filter(f => IMG_RE.test(f)).sort().map(f => `${urlBase}/${f}`)
}

export function discoverPageArt(page: string, fallback: string[] = []): string[] {
  const dir = path.join(process.cwd(), 'public', 'art', page)
  const found = listImages(dir, `/art/${page}`).filter(f => !f.includes('ui-overlay'))
  return found.length > 0 ? found : fallback
}

export function discoverPageOverlay(page: string): string | null {
  for (const ext of ['png', 'webp']) {
    const file = path.join(process.cwd(), 'public', 'art', page, `ui-overlay.${ext}`)
    if (fs.existsSync(file)) return `/art/${page}/ui-overlay.${ext}`
  }
  return null
}

export function splitAcrossChapters(images: string[], chapters: number): string[][] {
  if (images.length === 0) return Array.from({ length: chapters }, () => [])
  const result: string[][] = Array.from({ length: chapters }, () => [])
  images.forEach((img, i) => result[i % chapters].push(img))
  return result
}

export function toGalleryImages(
  srcs: string[],
  slug: string,
  label: string,
  minSlots = 6,
) {
  const total = Math.max(srcs.length, minSlots)
  return Array.from({ length: total }, (_, i) => ({
    id: `${slug}-${label}-${i}`,
    src: srcs[i] ?? undefined,
    caption: srcs[i] ? undefined : `${label} · ${i + 1}`,
  }))
}
